lightgallery.settings:
  type: config_object
  label: LightGallery Settings
  mapping:
    plugins:
      type: mapping
      label: Plugin settings
      mapping:
        core:
          type: mapping
          label: Core settings
          mapping:
            params:
              type: mapping
              label: Core parameters
              mapping:
                license_key:
                  type: string
                  label: License key
                  constraints:
                    NotBlank: {}
                    Regex:
                      pattern: /^[A-Z0-9]+(-[A-Z0-9]+)+$/
                      message: The license key is not valid.
                addClass:
                  type: string
                  label: Additional class
                allowMediaOverlap:
                  type: boolean
                  label: Allow media overlap
                appendCounterTo:
                  type: string
                  label: Append counter to
                appendSubHtmlTo:
                  type: string
                  label: Append sub HTML to
                backdropDuration:
                  type: integer
                  label: Backdrop duration
                closable:
                  type: boolean
                  label: Closable
                closeOnTap:
                  type: boolean
                  label: Close on tap
                controls:
                  type: boolean
                  label: Controls
                counter:
                  type: boolean
                  label: Counter
                defaultCaptionHeight:
                  type: integer
                  label: Default caption height
                download:
                  type: boolean
                  label: Download
                easing:
                  type: string
                  label: Easing
                enableDrag:
                  type: boolean
                  label: Enable drag
                enableSwipe:
                  type: boolean
                  label: Enable swipe
                escapeKey:
                  type: boolean
                  label: Escape key
                height:
                  type: string
                  label: Height
                hideBarsDelay:
                  type: integer
                  label: Hide bars delay
                hideControlOnEnd:
                  type: boolean
                  label: Hide control on end
                hideScrollbars:
                  type: boolean
                  label: Hide scrollbar
                iframeHeight:
                  type: string
                  label: Iframe height
                iframeMaxHeight:
                  type: string
                  label: Iframe max height
                iframeMaxWidth:
                  type: string
                  label: Iframe max width
                iframeWidth:
                  type: string
                  label: Iframe width
                index:
                  type: integer
                  label: Initial index
                isMobile:
                  type: boolean
                  label: Is mobile
                keyPress:
                  type: boolean
                  label: Key press
                loadYoutubePoster:
                  type: boolean
                  label: LAutomatically load poster image for YouTube videos
                loop:
                  type: boolean
                  label: Loop
                mode:
                  type: string
                  label: Mode
                mousewheel:
                  type: boolean
                  label: Mouse wheel
                nextHtml:
                  type: string
                  label: Next HTML
                prevHtml:
                  type: string
                  label: Previous HTML
                numberOfSlideItemsInDom:
                  type: integer
                  label: Number of slide items in DOM
                preload:
                  type: integer
                  label: Preload
                resetScrollPosition:
                  type: boolean
                  label: Reset scroll position
                showBarsAfter:
                  type: integer
                  label: Show bars after
                showCloseIcon:
                  type: boolean
                  label: Show close icon
                showMaximizeIcon:
                  type: boolean
                  label: Show maximize icon
                slideDelay:
                  type: integer
                  label: Slide delay
                slideEndAnimatoin:
                  type: boolean
                  label: Slide end animation
                speed:
                  type: integer
                  label: Speed
                swipeThreshold:
                  type: integer
                  label: Swipe threshold
                swipeToClose:
                  type: boolean
                  label: Swipe to close
                videoMaxSize:
                  type: string
                  label: Video max size
                width:
                  type: string
                  label: Width
                zoomFromOrigin:
                  type: boolean
                  label: Zoom from origin

        zoom:
          type: mapping
          label: Zoom plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Zoom
            params:
              type: mapping
              label: Zoom options
              mapping:
                actualSize:
                  type: boolean
                  label: Show actual size
                enableZoomAfter:
                  type: integer
                  label: Enable Zoom After
                infiniteZoom:
                  type: boolean
                  label: Infinite Zoom
                scale:
                  type: number
                  label: Zoom scale

        thumbnails:
          type: mapping
          label: Thumbnails plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Thumbnails
            params:
              type: mapping
              label: Thumbnails options
              mapping:
                alignThumbnails:
                  type: string
                  label: Align thumbnails
                animateThumb:
                  type: boolean
                  label: Animate thumbnails
                appendThumbnailsTo:
                  type: string
                  label: Append thumbnails to
                currentPagerPosition:
                  type: string
                  label: Current pager position
                enableThumbDrag:
                  type: boolean
                  label: Enable thumbnail drag
                enableThumbSwipe:
                  type: boolean
                  label: Enable thumbnail swipe
                loadYoutubeThumbnail:
                  type: boolean
                  label: Load YouTube thumbnail
                thumbHeight:
                  type: string
                  label: Thumbnail height
                thumbMargin:
                  type: integer
                  label: Thumbnail margin
                thumbWidth:
                  type: integer
                  label: Thumbnail width
                thumbnailSwipeThreshold:
                  type: integer
                  label: Thumbnail swipe threshold
                toggleThumb:
                  type: boolean
                  label: Toggle thumbnails
                youTubeThumbSize:
                  type: integer
                  label: YouTube thumbnail size

        video:
          type: mapping
          label: Video plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Video
            params:
              type: mapping
              label: Video options
              mapping:
                autoplayFirstVideo:
                  type: boolean
                  label: Autoplay first video
                autoplayVideoOnSlide:
                  type: boolean
                  label: Autoplay video on slide
                gotoNextSlideOnVideoEnd:
                  type: boolean
                  label: Go to next slide on video end
                youTubePlayer:
                  type: mapping
                  label: YouTube player parameters
                  mapping:
                    params:
                      type: mapping
                      label: YouTube player parameters
                      mapping:
                        modestbranding:
                          type: integer
                          label: Modest branding
                        rel:
                          type: integer
                          label: Related videos
                        showinfo:
                          type: integer
                          label: Show info
                        controls:
                          type: integer
                          label: Controls

        hash:
          type: mapping
          label: Hash plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Hash
            params:
              type: mapping
              label: Hash options
              mapping:
                customSlideName:
                  type: boolean
                  label: Custom slide name

        autoplay:
          type: mapping
          label: Autoplay plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Autoplay
            params:
              type: mapping
              label: Autoplay options
              mapping:
                appendAutoplayControlsTo:
                  type: string
                  label: Append autoplay controls to
                autoplayControls:
                  type: boolean
                  label: Show autoplay controls
                forceSlideShowAutoplay:
                  type: boolean
                  label: Force slideshow autoplay
                progessBar:
                  type: boolean
                  label: Progress bar
                slideShowAutoplay:
                  type: boolean
                  label: Slideshow autoplay
                slideShowDelay:
                  type: integer
                  label: Slideshow delay

        rotate:
          type: mapping
          label: Rotate plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Rotate
            params:
              type: mapping
              label: Rotate options
              mapping:
                flipHorizontal:
                  type: boolean
                  label: Flip horizontally
                flipVertical:
                  type: boolean
                  label: Flip vertically
                rotate:
                  type: boolean
                  label: Rotate
                rotateLeft:
                  type: boolean
                  label: Rotate left
                rotateRight:
                  type: boolean
                  label: Rotate right
                rotateStep:
                  type: integer
                  label: Rotate step

        pager:
          type: mapping
          label: Pager plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Pager

        fullscreen:
          type: mapping
          label: Fullscreen plugin
          mapping:
            enabled:
              type: boolean
              label: Enable Fullscreen
