lightgallery_thumbnail_formatter_settings:
  type: mapping
  label: lighGallery thumbnail formatter settings
  mapping:
    inline:
      type: boolean
      label: Inline gallery
    thumbnail_image_style:
      type: string
      label: Thumbnail image style
      nullable: true
    thumbnail_loading:
      type: string
      label: Thumbnail loading attribute
    gallery_image_style:
      type: string
      label: Gallery image style
      nullable: true
    custom_settings:
      type: sequence
      label: Custom settings

field.formatter.settings.image_lightgallery:
  type: lightgallery_thumbnail_formatter_settings
  label: Image lightGallery formatter settings
  mapping:
    title_as_caption:
      type: boolean
      label: Title as caption

field.formatter.settings.media_lightgallery:
  type: lightgallery_thumbnail_formatter_settings
  label: Media lightGallery formatter settings
  mapping:
    caption_view_mode:
      type: string
      label: Caption view mode
      nullable: true
